import java.util.Arrays;
import java.util.Locale;

public class Address {

    private String streetNum;
    private String streetName;
    private String apartmentNum;
    private String city;
    private String state;
    private String zipCode;

    //constructor 1, all fields
    public Address (String stN, String st, String aptN, String ct, String stat, String zip){
        streetNum = stN;
        streetName = st;
        apartmentNum = aptN;
        city = ct;
        state = stat;
        zipCode = zip;
    }
    //constructor 2, copy
    public Address (Address place){
        streetNum = place.getStreetNum();
        streetName = place.getStreetName();
        apartmentNum = place.getApartmentNum();
        city = place.getCity();
        state = place.getState();
        zipCode = place.getZipCode();
    }
    //constructor 3, string (format: XXXX StreetName APTN(optional), City, State ZipCode)
    public Address (String place){
        stringToAddress(place);
    }

    //getters
    public String getStreetNum() {
        return streetNum;
    }
    public String getStreetName() {
        return streetName;
    }
    public String getApartmentNum() {
        return apartmentNum;
    }
    public String getCity() {
        return city;
    }
    public String getState() {
        return state;
    }
    public String getZipCode() {
        return String.valueOf(zipCode);
    }

    //basic autogenerated setters
    public void setStreetNum(String streetNum) {
        this.streetNum = streetNum;
    }
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    public void setApartmentNum(String apartmentNum) {
        this.apartmentNum = apartmentNum;
    }
    public void setCity(String city) {
        this.city = city;
    }
    public void setState(String state) {
        this.state = state;
    }
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    //logic method for constructor, also serves as a mass modify
    public void stringToAddress (String place){
        int start = 0;
        int end = place.indexOf(" ");
        setStreetNum(place.substring(start, end));
        start = end+1;
        if (place.toLowerCase().contains("apt")){
            end = place.toLowerCase().indexOf("apt")-1;
            setStreetName(place.substring(start, end));
            start = end + 5;
            end = place.indexOf(",");
            setApartmentNum(place.substring(start, end));
        } else {
            end = place.indexOf(",");
            setStreetName(place.substring(start, end));
        }
        start = end+2;
        end = start + place.substring(start).indexOf(",");
        setCity(place.substring(start, end));
        start = end+2;
        end = start+2;
        setState(place.substring(start,end));
        start = end + 1;
        setZipCode(place.substring(start));
    }

    //toString method for Address
    public String toString() {
        String temp = getStreetNum() + " " + getStreetName();
        if (apartmentNum != null){
            temp += " Apt " + apartmentNum;
        }
        temp += ", " + getCity() + ", " + getState() + " " + getZipCode();
        return temp;
    }
}
